import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
import { product1, product2, product3, product4, product5, product6, product7,product8, product9, product10, product11, product12, product13, product14, product15, product16, product17, product18, product19, product20, product21, product22, product23, product24, product25, product26, product27 } from '../../assets/index.js'

export const products = [
  
  {
    id: "0M0x1",
    title: "Nike Air Low Premium",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product7,
    price: "150",
    color: "from-sky-600 to-indigo-600",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    id: "0M0x2",
    title: "Nike Air Force Green",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product2,
    price: "150",
    color: "from-green-500 to-emerald-500",
    shadow: "shadow-lg shadow-green-500",
  },
  {
    id: "0M0x3",
    title: "Nike Addapt BB Rose",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product3,
    price: "150",
    color: "from-red-500 to-rose-500",
    shadow: "shadow-lg shadow-rose-500",
  },
  {
    id: "0M0x4",
    title: "Nike Air Premium",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product4,
    price: "150",
    color: "from-orange-500 to-amber-500",
    shadow: "shadow-lg shadow-orange-500",
  },
  {
    id: "0M0x5",
    title: "Nike Adapt BB Pro",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product5,
    price: "150",
    color: "from-gray-900 to-yellow-500",
    shadow: "shadow-lg shadow-yellow-500",
  },
  {
    id: "0M0x6",
    title: "Air Jordan PR3",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product6,
    price: "150",
    color: "from-blue-500 to-cyan-500",
    shadow: "shadow-lg shadow-cyan-500",
  },
  {
    id: "0M0x7",
    title: "Nike Multi Smart Shoe",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product1,
    price: "150",
    color: "from-yellow-500 to-yellow-500",
    shadow: "shadow-lg shadow-yellow-500",
  },
  {
    id: "0M0x8",
    title: "Nike Jordan Air Max",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product9,
    price: "150",
    color: "from-[#936550] to-orange-900",
    shadow: "shadow-lg shadow-orange-800",
  },
  {
    id: "0M0x9",
    title: "Nike Old Max-x",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product10,
    price: "150",
    color: "from-indigo-700 to-indigo-700",
    shadow: "shadow-lg shadow-indigo-500",
  },
  {
    id: "0M0x10",
    title: "Nike Lime Jordan 11",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product12,
    price: "150",
    color: "from-green-600 to-lime-500",
    shadow: "shadow-lg shadow-lime-500",
  },
  {
    id: "0M0x11",
    title: "Nike Air Black Max",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product11,
    price: "150",
    color: "from-slate-900 to-black",
    shadow: "shadow-lg shadow-black",
  },
  {
    id: "0M0x12",
    title: "Nike Zoom Max",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product8,
    price: "150",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },

  // more data

  //puma starts
  {
    id: uuid(),
    title: "Runtamed Plus",
    text: "Women's Sneakers",
    brand: 'puma',
    rating: "5+",
    btn: "Buy Now",
    img: product13,
    price: "150",
    color: "from-sky-600 to-indigo-600",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    id:uuid(),
    title: "Mercedes AMG Petronas",
    text: "MEN's Sneakers",
    brand: 'puma',
    rating: "5+",
    btn: "Buy Now",
    img: product14,
    price: "150",
    color: "from-green-500 to-emerald-500",
    shadow: "shadow-lg shadow-green-500",
  },
  {
    id:uuid(),
    title: "Puma x LAMELO BALL MB.02",
    text: "MEN's Basketball Shoes",
    brand: 'puma',
    rating: "5+",
    btn: "Buy Now",
    img: product15,
    price: "150",
    color: "from-red-500 to-rose-500",
    shadow: "shadow-lg shadow-rose-500",
  },
  {
    id:uuid(),
    title: "One8 Virat Kohli Shuffle V3",
    text: "MEN Sneakers",
    brand: 'puma',
    rating: "5+",
    btn: "Buy Now",
    img: product16,
    price: "150",
    color: "from-orange-500 to-amber-500",
    shadow: "shadow-lg shadow-orange-500",
  },
  {
    id:uuid(),
    title: "Slipstream Lo Super Comic",
    text: "Unisex Sneakers",
    brand: "puma",
    rating: "5+",
    btn: "Buy Now",
    img: product17,
    price: "150",
    color: "from-gray-900 to-yellow-500",
    shadow: "shadow-lg shadow-yellow-500",
  },
  {
    id:uuid(),
    title: "Air Jordan PR3",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product18,
    price: "150",
    color: "from-blue-500 to-cyan-500",
    shadow: "shadow-lg shadow-cyan-500",
  },

  // puma ends
  {
    id:uuid(),
    title: "Adidas Superstar Shoes",
    text: "MEN Sneakers",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product19,
    price: "150",
    color: "from-yellow-500 to-yellow-500",
    shadow: "shadow-lg shadow-yellow-500",
  },
  {
    id:uuid(),
    title: "NMD_R1 SHOES",
    text: "MEN Running Shoes",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product20,
    price: "150",
    color: "from-[#936550] to-orange-900",
    shadow: "shadow-lg shadow-orange-800",
  },
  {
    id:uuid(),
    title: "OZTRAL SHOES",
    text: "Unisex Sneakers",
    brand: 'adidas',
    rating: "5+",
    btn: "Buy Now",
    img: product21,
    price: "150",
    color: "from-indigo-700 to-indigo-700",
    shadow: "shadow-lg shadow-indigo-500",
  },
  {
    id: uuid(),
    title: "FORUM MID",
    text: "MEN Basketball Shoes",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product22,
    price: "150",
    color: "from-green-600 to-lime-500",
    shadow: "shadow-lg shadow-lime-500",
  },
  {
    id: uuid(),
    title: "FORUM 84 HIGH SHOES",
    text: "MEN Originals",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product23,
    price: "150",
    color: "from-slate-900 to-black",
    shadow: "shadow-lg shadow-black",
  },
  {
    id: uuid(),
    title: "NMD_S1 SHOES",
    text: "Men Originals",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product24,
    price: "150",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    id: uuid(),
    title: "SK8-HI",
    text: "Women Originals",
    brand: "vans",
    rating: "5+",
    btn: "Buy Now",
    img: product25,
    price: "150",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    id: uuid(),
    title: "SK8-HI CANVAS/SUED",
    text: "Men Originals",
    brand: "vans",
    rating: "5+",
    btn: "Buy Now",
    img: product26,
    price: "150",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    id: uuid(),
    title: "SENTRY SK8-HI WC",
    text: "Men Originals",
    brand: "vans",
    rating: "5+",
    btn: "Buy Now",
    img: product27,
    price: "150",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    id: uuid(),
    title: "NMD_S1 SHOES",
    text: "Men Originals",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product24,
    price: "150",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
]
