import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
import { product1, product2, product3, product4, product5, product6, product7,product8, product9, product10, product11, product12, product13, product14, product15, product16, product17, product18, product19, product20, product21, product22, product23, product24, product25, product26, product27, psale1, psale2, psale3 } from '../../assets/index.js'

export const products = [
  
  {
    _id: "1",
    title: "Nike Air Low Premium",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product7,
    price: "6999",
    color: "from-sky-600 to-indigo-600",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    _id: "2",
    title: "Nike Air Force Green",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product2,
    price: "9899",
    color: "from-green-500 to-emerald-500",
    shadow: "shadow-lg shadow-green-500",
  },
  {
    _id: "3",
    title: "Nike Addapt BB Rose",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product3,
    price: "1999",
    color: "from-red-500 to-rose-500",
    shadow: "shadow-lg shadow-rose-500",
  },
  {
    _id: "4",
    title: "Nike Air Premium",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product4,
    price: "9999",
    color: "from-orange-500 to-amber-500",
    shadow: "shadow-lg shadow-orange-500",
  },
  {
    _id: "5",
    title: "Nike Adapt BB Pro",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product5,
    price: "999",
    color: "from-gray-900 to-yellow-500",
    shadow: "shadow-lg shadow-yellow-500",
  },
  {
    _id: "6",
    title: "Air Jordan PR3",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product6,
    price: "2999",
    color: "from-blue-500 to-cyan-500",
    shadow: "shadow-lg shadow-cyan-500",
  },
  {
    _id: "7",
    title: "Nike Multi Smart Shoe",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product1,
    price: "5999",
    color: "from-yellow-500 to-yellow-500",
    shadow: "shadow-lg shadow-yellow-500",
  },
  {
    _id: "8",
    title: "Nike Jordan Air Max",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product9,
    price: "4599",
    color: "from-[#936550] to-orange-900",
    shadow: "shadow-lg shadow-orange-800",
  },
  {
    _id: "9",
    title: "Nike Old Max-x",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product10,
    price: "2599",
    color: "from-indigo-700 to-indigo-700",
    shadow: "shadow-lg shadow-indigo-500",
  },
  {
    _id: "10",
    title: "Nike Lime Jordan 11",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product12,
    price: "6969",
    color: "from-green-600 to-lime-500",
    shadow: "shadow-lg shadow-lime-500",
  },
  {
    _id: "11",
    title: "Nike Air Black Max",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product11,
    price: "8599",
    color: "from-slate-900 to-black",
    shadow: "shadow-lg shadow-black",
  },
  {
    _id: "12",
    title: "Nike Zoom Max",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: product8,
    price: "10000",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    _id: "13",
    title: "Nike Addapt BB 2.0",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "4.9",
    btn: "Buy Now",
    img: psale2,
    price: "1999",
    color: "from-blue-600 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  // psale1
  {
    _id: "14",
    title: "Nike Martine Rose",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "4.5", 
    btn: "Buy Now",
    img: psale1,
    price: "1299",
    color: "from-red-500 to-rose-500",
    shadow: "shadow-lg shadow-rose-500",
  },
  {
    _id: "15",
    title: "Nike Smart Shoe 2.0",
    text: "MEN Running Shoes",
    brand: "nike",
    rating: "5+",
    btn: "Buy Now",
    img: psale3,
    price: "1099",
    color: "from-violet-500 to-indigo-500",
    shadow: "shadow-lg shadow-violet-500",
  },

  // more data

  //puma starts
  {
    _id: "16",
    title: "Runtamed Plus",
    text: "Women's Sneakers",
    brand: 'puma',
    rating: "5+",
    btn: "Buy Now",
    img: product13,
    price: "4599",
    color: "from-sky-600 to-indigo-600",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    _id: "17",
    title: "Mercedes AMG Petronas",
    text: "MEN's Sneakers",
    brand: 'puma',
    rating: "5+",
    btn: "Buy Now",
    img: product14,
    price: "3999",
    color: "from-green-500 to-emerald-500",
    shadow: "shadow-lg shadow-green-500",
  },
  {
    _id: "18",
    title: "Puma x LAMELO BALL MB.02",
    text: "MEN's Basketball Shoes",
    brand: 'puma',
    rating: "5+",
    btn: "Buy Now",
    img: product15,
    price: "9999",
    color: "from-red-500 to-rose-500",
    shadow: "shadow-lg shadow-rose-500",
  },
  {
    _id: "19",
    title: "One8 Virat Kohli Shuffle V3",
    text: "MEN Sneakers",
    brand: 'puma',
    rating: "5+",
    btn: "Buy Now",
    img: product16,
    price: "7599",
    color: "from-orange-500 to-amber-500",
    shadow: "shadow-lg shadow-orange-500",
  },
  {
    _id: "20",
    title: "Slipstream Lo Super Comic",
    text: "Unisex Sneakers",
    brand: "puma",
    rating: "5+",
    btn: "Buy Now",
    img: product17,
    price: "6999",
    color: "from-gray-900 to-yellow-500",
    shadow: "shadow-lg shadow-yellow-500",
  },
  {
    _id: "21",
    title: "Air Jordan PR3",
    text: "MEN Running Shoes",
    rating: "5+",
    btn: "Buy Now",
    img: product18,
    price: "4899",
    color: "from-blue-500 to-cyan-500",
    shadow: "shadow-lg shadow-cyan-500",
  },

  // puma ends
  {
    _id: "22",
    title: "Adidas Superstar Shoes",
    text: "MEN Sneakers",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product19,
    price: "3499",
    color: "from-yellow-500 to-yellow-500",
    shadow: "shadow-lg shadow-yellow-500",
  },
  {
    _id: "23",
    title: "NMD_R1 SHOES",
    text: "MEN Running Shoes",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product20,
    price: "2499",
    color: "from-[#936550] to-orange-900",
    shadow: "shadow-lg shadow-orange-800",
  },
  {
    _id: "24",
    title: "OZTRAL SHOES",
    text: "Unisex Sneakers",
    brand: 'adidas',
    rating: "5+",
    btn: "Buy Now",
    img: product21,
    price: "2999",
    color: "from-indigo-700 to-indigo-700",
    shadow: "shadow-lg shadow-indigo-500",
  },
  {
    _id: "25",
    title: "FORUM MID",
    text: "MEN Basketball Shoes",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product22,
    price: "89999",
    color: "from-green-600 to-lime-500",
    shadow: "shadow-lg shadow-lime-500",
  },
  {
    _id: "26",
    title: "FORUM 84 HIGH SHOES",
    text: "MEN Originals",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product23,
    price: "5499",
    color: "from-slate-900 to-black",
    shadow: "shadow-lg shadow-black",
  },
  {
    _id: "27",
    title: "NMD_S1 SHOES",
    text: "Men Originals",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product24,
    price: "9499",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    _id: "28",
    title: "SK8-HI",
    text: "Women Originals",
    brand: "vans",
    rating: "5+",
    btn: "Buy Now",
    img: product25,
    price: "10000",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    _id: "29",
    title: "SK8-HI CANVAS/SUED",
    text: "Men Originals",
    brand: "vans",
    rating: "5+",
    btn: "Buy Now",
    img: product26,
    price: "3000",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    _id: "30",
    title: "SENTRY SK8-HI WC",
    text: "Men Originals",
    brand: "vans",
    rating: "5+",
    btn: "Buy Now",
    img: product27,
    price: "1499",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
  {
    _id: "31",
    title: "NMD_S1 SHOES",
    text: "Men Originals",
    brand: "adidas",
    rating: "5+",
    btn: "Buy Now",
    img: product24,
    price: "1199",
    color: "from-blue-900 to-blue-500",
    shadow: "shadow-lg shadow-blue-500",
  },
]
