export const ActionType = {
  INITIALZE_PRODUCTS: "INITIALIZE_PRODUCTS",
  // INITIALZE_HOME_PRODUCTS: "INITIALZE_HOME_PRODUCTS",
  SET_CART: "SET_CART",
  SET_WISHLIST: "SET_WISHLIST",
  FILTER_CHANGE: "FILTER",
  SEARCH_FILTER: "SEARCH_FILTER",
  CLEAR_FILTER: "CLEAR_FILTER",
  ADD_ADDRESS: "ADD_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS"
}